### ISSUE TITLE
Enable 4pol+minV calibration

### ISSUE THREAD

**Issue by SaulAryehKohn** [HERA-Team/hera_cal#32]
Right now specifying the `--minV` option in `omni_run` causes the below error, since we overload certain redundancy arrays to tell omnical that xy and yx visibilities are redundant, causing pyuvdata to freak out.

```
Traceback (most recent call last):
  File "/users/plaplant/hera/heracal/scripts/omni_run.py", line 11, in <module>
    omni.omni_run(files, opts, history)
  File "/users/plaplant/anaconda2/envs/capo_sak/lib/python2.7/site-packages/heracal-0.0.0-py2.7.egg/heracal/omni.py", line 1242, in omni_run
    fsj, force_phase=True, spoof_nonessential=True)
  File "/users/plaplant/anaconda2/envs/capo_sak/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvdata.py", line 950, in write_uvfits
    run_check_acceptability=run_check_acceptability)
  File "/users/plaplant/anaconda2/envs/capo_sak/lib/python2.7/site-packages/pyuvdata-1.1-py2.7.egg/pyuvdata/uvfits.py", line 349, in write_uvfits
    raise ValueError('The polarization values are not evenly spaced (probably '
ValueError: The polarization values are not evenly spaced (probably because of a select operation). The uvfits format does not support unevenly spaced polarizations.
```

(FYI the `capo_sak` isn't actually referring to the `capo` repository, it's the name of an anaconda environment.)

**Comment by jsdillon** [comment]
Hold off on this until we figure out whether we actually want MinV.

**Comment by SaulAryehKohn** [comment]
Ok, but FWIW see PR #48
