### ISSUE TITLE
SVD Convergence Error in hera_cal.redcal.RedundantCalibrator.lincal

### ISSUE THREAD

**Issue by AaronParsons** [HERA-Team/hera_cal#55]
At least on my numpy version (1.14.0.dev0+33ce0ba), hera_cal.redcal.RedundantCalibrator.lincal raises an exception for solvable systems of equations when the datatypes are np.complex64 instead of np.complex128.  In the branch 'svd_converge_err' I have an addition to test_redcal.py that exposes this error.  On my machine, it errors out with:

ERROR: test_svd_convergence (__main__.TestRedundantCalibrator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_redcal.py", line 180, in test_svd_convergence
    meta, sol = rc.lincal(d, sol0) # will raise np.linalg.linalg.LinAlgError: SVD did not converge
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/hera_cal-0.0.0-py2.7.egg/hera_cal/redcal.py", line 121, in lincal
    meta, sol = ls.solve_iteratively(conv_crit=conv_crit, maxiter=maxiter)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/linsolve-0.0.1-py2.7.egg/linsolve/__init__.py", line 480, in solve_iteratively
    new_sol = self.solve()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/linsolve-0.0.1-py2.7.egg/linsolve/__init__.py", line 455, in solve
    dsol = self.ls.solve(rcond=rcond, verbose=verbose)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/linsolve-0.0.1-py2.7.egg/linsolve/__init__.py", line 292, in solve
    AtAi = np.linalg.pinv(AtA, rcond=rcond)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.14.0.dev0+33ce0ba-py2.7-macosx-10.9-x86_64.egg/numpy/linalg/linalg.py", line 1647, in pinv
    u, s, vt = svd(a, 0)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.14.0.dev0+33ce0ba-py2.7-macosx-10.9-x86_64.egg/numpy/linalg/linalg.py", line 1389, in svd
    u, s, vt = gufunc(a, signature=signature, extobj=extobj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/numpy-1.14.0.dev0+33ce0ba-py2.7-macosx-10.9-x86_64.egg/numpy/linalg/linalg.py", line 99, in _raise_linalgerror_svd_nonconvergence
    raise LinAlgError("SVD did not converge")
LinAlgError: SVD did not converge

**Comment by AaronParsons** [comment]
I can confirm that this error still happens for numpy 1.13.0rc1 as well.

**Comment by plaplant** [comment]
I also get a non-convergence error on my local machine. I'm using numpy v.1.13.1 from anaconda, which links against the MKL libraries from anaconda, so I think it's a different backend from yours. I also only get a convergence error for single-precision numbers. This makes me suspect it's a particularly poorly conditioned matrix. @AaronParsons can you extract the matrix you're trying to get the SVD of? I'm curious to see if external libraries (e.g. MATLAB or Mathematica) also have difficulty. That said, is there a problem with using double-precision numbers?

**Comment by AaronParsons** [comment]
I'll work on getting this, but in making apple-to-apple comparisons of redcal with omnical, I need to be able to use single-precisions numbers.  Omnical is able to invert this matrix, somehow, although the matrix itself may be constructed slightly differently under the hood.

**Comment by jsdillon** [comment]
Unless we want to move back to single precision, we now understand that this is due to Omnical not actually inverting the matrix, so we can close the issue since there's nothing to fix.
